### ISSUE TITLE
Improve synching 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2509]
There are things that currently don't sync between browser. This issue is to keep track of them. 

- [x] Notifications unread 
- [x] Favorite docker containers
- [x] Visible / hidden keys for JSON logs 
- [ ] Sort order on homepage

**Comment by amir20** [comment]
@EDIflyer Add anything you might also think of...

**Comment by EDIflyer** [comment]
That seems pretty comprehensive! I think everything else on the main settings page is already covered?

BTW just found your guide re following log files from disk (https://dozzle.dev/guide/log-files-on-disk) - absolutely brilliant, really love it!  Going to create a wee docker compose for the ones I like to routine follow so they survive restart, but the docker run command works well.

**Comment by EDIflyer** [comment]
@amir20 done in #2511  ;)

**Comment by amir20** [comment]
Hmm this is a little more complicated than I thought. I was hoping to do one solution that fixes all synching. Will have to rethink this.

**Comment by amir20** [comment]
I have merged to master and releasing. This should be out soon.

**Comment by EDIflyer** [comment]
Just tried on an existing install that updated overnight - one minor 🐛that I noticed:

1. Logged into Dozzle site (via Authelia)
2. Favourited one container
3. Moved across to second browser (fresh setup, all site data/cookies cleared) and logged in to site
4. Favourited container was showing up OK but colour scheme had gone back to auto and was in light mode
5. In existing browser (where dark mode was already set) I flicked scrollbars off/on in the settings screen
6. Then refreshed on the second browser and it all updated appropriately
7. I then closed the browser (which is set to wipe everything at close) and when I reopened and went back in it was all looking fine with favourited container and saved settings

I tried the above on a second site and it was reproducible.

Not sure if helpful or something to fix (given it seemed to easily get sorted) but thought I should flag!

**Comment by EDIflyer** [comment]
Ah OK - that makes sense and fits with having to have saved one setting to trigger the settings into the new `profile.json`.  I agree no point in coding a whole transition when there are relatively few settings.

One slightly weird thing I've noticed now is around pinning/unpinning a container...
1. Pin (favourite/start) container on browser 2
2. Refresh (F5) on browser 1 - shows up OK
3. Unpin same container on browser 2 - refresh on browser 1 - no change, still pinned
4. Pin a different container on browser 2 - refresh on browser 1 - new container pinned, old one unpinned
5. Repeat and when number of containers pinnned is >1 it works fine, unpinning is reflected in the other browser with refresh
6. However if number of containers pinned=1 then unpinning has no effect

Hope I'm describing it clearly but there's something different when trying to return to 0 pinned containers vs n>1 pinned containers when it works as expected!

**Comment by amir20** [comment]
Hmm, that is weird. I haven't tested those exact steps. Will have to test it and see what's different. I thought I would always overwrite but maybe I am doing something different.

**Comment by EDIflyer** [comment]
Just to flag that the above behaviour is still happening in 5.6.1 for me - for favourites containers >1 then adding/removing works perfectly but when down to 1 container it won't sync going back to 0 favourites and you have to manually remove it on each other browser.

I've done a wee bit more testing - if I pin on browser 1, then refresh on browser 2 then unpin on browser 1 then refresh browser 2 again (which is already logged in) then it won't unpin it.  However if I open a fresh browser it doesn't show as pinned - however browser 2 persists the pinning even if I close the tab and reopen it, so it seems like it's more the running instance isn't properly recognising/syncing the removal rather than it not being synced to the server (given fresh browsers reflect it correctly).  Hope that helps/makes sense!
