### ISSUE TITLE
Improvements to loggings 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#3229]
### Describe the feature you would like to see

I have been thinking of a couple improvements to log view that I want to cover this in feature.

**Comment by amir20** [comment]
Currently, this progress bar is how much content is in the browser. I think this number should actually be changed to how much logs are available to be fetched. 

<img width="188" alt="Screenshot 2024-08-25 at 8 26 10 AM" src="https://github.com/user-attachments/assets/a307274a-5e63-4230-b75d-88a4a4a372b7">

So if now is Aug 25th, and the container was started seven days ago, the progress bar would be at 0% seven days ago and 100% today.

**Comment by amir20** [comment]
Add some UI indication when in live mode.  See https://github.com/amir20/dozzle/issues/3225#issuecomment-2308164373

I have no idea what this could look like. But I like this suggestion by @FrancYescO

**Comment by amir20** [comment]
Last one, try again to fetch more when zero logs are returned. This is also covered https://github.com/amir20/dozzle/issues/3222

**Comment by amir20** [comment]
I liked the idea of pulsing bar. I have something https://github.com/amir20/dozzle/pull/3231


https://github.com/user-attachments/assets/9dbc9f7c-c28f-49f9-a1ca-5f5d43999d31

**Comment by amir20** [comment]
@FrancYescO I have merged 3 PRs in `master`: 

- #3231 which adds the animation while live 
- #3230 which tries to retry. (Haven't really tested this yet). This closes the other bug
- #3227 which should the perf improvement. 

You should be able to test all these with `amir20/dozzle:master`. 

Improving the progress bar will be more work so I'll work on that when I have some free time.

**Comment by amir20** [comment]
In light mode, the bar looks very faded 🫠. I'll worry about it later...

**Comment by FrancYescO** [comment]
I think all issue are fixed, i can also confirm that the performance will get worse when a lot of messages are loaded in the ui (lot of scrolling up, also the scroll down will be lagghish) so the real game changer was to make the buffer smaller as you said

just a minor thing , i'm using the compact mode and i think these gaps can be totally removed :P
![image](https://github.com/user-attachments/assets/1320a967-58e7-41cc-b66a-472c96bd66bb)
`padding-bottom: 1rem;`

idk why happened, i was in live mode, and i still got few "skipped xxx messages"
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/631e57b5-6f2e-4f2c-9659-627bdd377d5d">
looks like that after i've loaded some messages in the past the live mode is not working correctly until a refresh

**Comment by amir20** [comment]
Still working on padding and stuff....

> idk why happened, i was in live mode, and i still got few "skipped xxx messages"

I haven't changed anything in that logic but I will pay attention if it happens. 


Looks like I introduced a bug where if there actually isn't any messages then it does an infinite loops. :P

**Comment by amir20** [comment]
I did the scroll progress where the progress reflects the total logs available. It's pretty amazing. I don't know why I didn't think about this before. 

See https://github.com/amir20/dozzle/pull/3236

**Comment by FrancYescO** [comment]
> I haven't changed anything in that logic but I will pay attention if it happens.

maybe is something related to scrolling, something like "if not scroll automatically fast enought during bust the skip message will popup" is pretty replicable on my logs (also if i never scroll up to load something older) and now i can surely say that is not myself that have scrolled up a little

> Looks like I introduced a bug where if there actually isn't any messages then it does an infinite loops. :P
i thinked about it, but i have not reached the start of logs to test :D

**Comment by amir20** [comment]
Merging last PR. For now I am going to resolve this. @FrancYescO can you keep trying `master` over the next few days and let me know if you have any big bugs?

**Comment by FrancYescO** [comment]
maybe i misunderstood something... but my percentage seems is still related to logs in browser and not from the created date of the container also in the actual master tag

except this more the once also if pulsating bar was there log where not coming and i had to switch the container or refresh to get last logs... i haven't found an easy replicable path but this is happening often to me on container that have irregular logs this is a 2min count:
```
   4 2024-08-26T17:56:22
 340 2024-08-26T17:57:25
 436 2024-08-26T17:57:26
 536 2024-08-26T17:57:27
 476 2024-08-26T17:57:28
 544 2024-08-26T17:57:29
 544 2024-08-26T17:57:30
 528 2024-08-26T17:57:31
  80 2024-08-26T17:57:32
 376 2024-08-26T17:57:37
   4 2024-08-26T17:57:39
 312 2024-08-26T17:58:42
 416 2024-08-26T17:58:43
 528 2024-08-26T17:58:44
 456 2024-08-26T17:58:45
 564 2024-08-26T17:58:46
 568 2024-08-26T17:58:47
 572 2024-08-26T17:58:48
  68 2024-08-26T17:58:49
   4 2024-08-26T17:58:53
 372 2024-08-26T17:58:54
   4 2024-08-26T17:58:56
 356 2024-08-26T17:59:59
```

note that there are a lot of seconds missing = 0 entries

**Comment by amir20** [comment]
Oh hmmm on a related note, I do see the bug you were talking about before. Seems like skipped logs shows up even when live.

**Comment by amir20** [comment]
That might have been a stupid bug which now fixed with  0798de3b.

Wait 5 minutes and try again with `master`.

**Comment by FrancYescO** [comment]
> <img width="126" alt="Screenshot 2024-08-26 at 1 29 55 PM" src="https://github.com/user-attachments/assets/6f5b4ee2-7eb5-4576-816c-9e0105f1d3fd">
> 
> 
> 
> Do you have the latest version? You should see a little new text now like `3 minutes ago`. 
> 
> 
> 
> 

Yup i've wait for the CI, i was also testing the pr tag but i noticed no difference, btw going to retry soon, maybe some browser cache...

**Comment by amir20** [comment]
I probably should put the git version for master. 🤷🏼‍♂️

**Comment by FrancYescO** [comment]
ok i can confirm that is now working on master... maybe adding decimals to the percentage can be useful (or maybe still not in my case...): i scrolled a bit but i was still at 100% :P

also idk if something is different but i noticed on mobile it appear a lot smoother when scrolling with a lot of log loaded
