### ISSUE TITLE
Mouse wheel scroll issues in pinned-mode

### ISSUE THREAD

**Issue by 726a67** [amir20/dozzle#547]
**Describe the bug**
When a set of logs is pinned, the ability to scroll up through any/all displayed logs using the mouse wheel is lost. Scrolling down using the mouse wheel functions as expected.

**To Reproduce**
1. Go to the Dozzle web interface.
2. Click on the 'pin' icon for any listed container.
3. Attempt to scroll up through the container's logs using the mouse wheel.

**Expected behavior**
Logs should scroll up or down using when using the mouse wheel, regardless of whether or not any logs are pinned.

**Desktop (please complete the following information):**
 - OS: Windows 10 (client), Centos 7 (Dozzle host)
 - Docker version: 19.03.12, build 48a66213fe (Dozzle host)
 - Browser & version: Firefox 77.0.1 (64-bit)
 - Version: 2.0.2

**Comment by amir20** [comment]
Hmm I don't use a Windows. On my Mac, Firefox and scroll gesture works. 

@726a67 Do you think you can help him investigate? If I can't reproduce it then I won't be able to fix it. FWIW, I don't do anything special when pinned. I just create a new `div` with `overflow:scroll`.

**Comment by 726a67** [comment]
Sure, happy to help if I can. Is there anything in particular you'd like me to try?

Since opening the issue I've additionally tested the functionality with both Chrome (83.0.4103.97) and Edge (83.0.478.56) -- both behave normally.

Additional testing through Firefox (private window, safe mode, new profile, etc.) yields the same result, however.

**Comment by amir20** [comment]
I believe I found the issue. This is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1043520) with Firefox which seems to be fixed in other browsers. This [stackoverflow](https://stackoverflow.com/questions/28636832/firefox-overflow-y-not-working-with-nested-flexbox) post suggests a fix. 

Do you know enough CSS to give it a try? Since I don't have a Windows machine I can't test it. If I understand correctly, you need to add `min-height:0;` to the parent of `<main>` which is `section.is-full-height-scrollable`. 

This does seem to only happen with Firefox.

**Comment by 726a67** [comment]
@amir20 

Yep, that fixed it. I only modified the CSS running in my browser, however -- will you be able to roll it out server-side?

**Comment by amir20** [comment]
So to be clear, you added `min-height:0` to `section.is-full-height-scrollable`?

**Comment by 726a67** [comment]
Yeah, here is the pertinent CSS straight out of my browser:

```
section.is-full-height-scrollable[data-v-710546b2]{
    height:100vh
    min-height:0;
}
```

**Comment by amir20** [comment]
OK great. Building right now.

**Comment by amir20** [comment]
OK give `latest-dev` a try. https://hub.docker.com/repository/registry-1.docker.io/amir20/dozzle/builds/e2b2a920-a99c-4d67-9eb0-ebc10dc1fed2

**Comment by amir20** [comment]
If it works, I can release the next patch. There were also two other bugs I found with testing in Firefox which were recently fixed.

**Comment by 726a67** [comment]
Hmm...

`section.is-full-height-scrollable[data-v-710546b2]{height:100vh;min-height:0}`

Again, this is the CSS straight from my browser (using latest-dev). However this time, up-scrolling is still broken.

**Comment by amir20** [comment]
Hm. This is confusing. I am creating an official release right now because I broke something else. But I didn't think it would affect this. 

If you remove that style and then add it back in, does it work?

**Comment by 726a67** [comment]
Strangely enough, if I remove min-height (or even change its value to any random number), the up-scroll works for a page or two, and then stops working again. The down-scroll works regardless. Really weird stuff, lol.

**Comment by amir20** [comment]
One of the comments on that stackoverflow post says..

> It potentially needs to be applied to every ancestor that is a flex item (i.e. every ancestor whose 
parent is display:flex), depending on the circumstances

But that seems like an overkill. I'll have to keep researching this. Not being able to test it makes it even more challenging.

**Comment by 726a67** [comment]
Yeah, I definitely understand where you're coming from. In any event, I'm happy to keep pulling from latest-dev to test any potential fixes you want to roll out for this issue, or if you have specific CSS snippets you'd like me to test in-browser, I can provide feedback there as well.

**Comment by amir20** [comment]
Well it's confusing because it sounds like when you add some CSS it works but when the page loads with that CSS it doesn't work. Soooo I am not sure how to even go about figuring that out. 

I'll try with VirtualBox but that probably won't work since it's not a real mouse wheel.

**Comment by amir20** [comment]
@726a67 I was sort of able to reproduce this. I installed VirtualBox with Windows 10. I was able to scroll up and down at first, then locked it to the bottom and was not able to scroll anymore, which was weird. But then it started working again when I used the scrollbar. 

I can't tell if my virtual box is just really slow or it's actually a bug. I'll keep this bug open for now as reproduced. I hope someone else can invest in this bug to help debug.

**Comment by 726a67** [comment]
@amir20 Sure thing.

Just to be clear, I've never had a problem using the **scrollbar** -- that is, clicking the up/down arrows on the bar or clicking+dragging the bar. These always worked as expected.

For me, the issue only manifests when attempting to use the **mousewheel** to scroll up inside of a pinned log-set. Without pinned logs, this too works as expected.

**Comment by amir20** [comment]
Right, that's what I thought you meant. When there is only one container I actually leverage the browser's native scrollers. This seemed the the right thing as most people are not pinning containers. Only when more than one container is logged, I created a div with `overflow:auto`. This also made sense when using mobile devices because using the native scrollers worked best. 

Anyway, I'd like to fix this eventually. I fixed a few other Firefox bugs. For now, I don't have the tools to investigate.

**Comment by 726a67** [comment]
Just checking in 1) to let you know that this CSS issue is still occurring in Firefox 91 and 2) to ask if you've been able to acquire the tooling needed to debug. If not, no biggie!

**Comment by amir20** [comment]
No update and no one else has filed similar bugs.

**Comment by Coteh** [comment]
Was just about to file a duplicate of this bug when I thought last second to search for it first lol.

This bug still exists for me, but on Firefox 96.0.3 (64-bit) running on macOS Catalina v10.15.7. It works on Chrome 98.0.4758.80 and Safari 15.2 (15612.3.6.1.8, 15612) however.

I don't recall experiencing it on Windows 10 Firefox but I can look out for it tomorrow.

**Comment by Coteh** [comment]
Can confirm that Firefox 96.0.3 (64-bit) on Windows 10 does not work either. But it works on Chrome 98.0.4758.81 and Edge Chromium 98.0.1108.43.

However, on my Microsoft Surface tablet, I can still use the trackpad or touchscreen to scroll up when in the split pane view.
